version: '3.8'

services:
  api:
    image: lombokhalalroom/lombok-halal-room-api-jenkins:latest
    container_name: lhr-api-jenkins
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
